apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: kumari3123/wordpress-custom:20
          ports:
            - containerPort: 80
          env:
           - name: WORDPRESS_DB_HOST
             value: "mysql-service"
           - name: WORDPRESS_DB_USER
             value: "wordpress"
           - name: WORDPRESS_DB_PASSWORD
             value: "aixop4kY6iEl"
           - name: WORDPRESS_DB_NAME
             value: "wordpress"
