apiVersion: v1
kind: Service
metadata:
  name: mysql-service # <--- This name is the host WordPress will look for!
  labels:
    app: mysql
spec:
  ports:
    - port: 3306 
  selector:
    app: mysql
  type: ClusterIP
